language: c

install:
  - pip install --user cmake

before_script:
  - git clone https://github.com/ThrowTheSwitch/Unity.git ~/Unity
  - mkdir build
  - cd build

script:
  - cmake -D BITLOOM_ROOT=~ ..
  - make
  - ./bitloom-costumes-test -v

